{
    'name' : 'Ilexius task',
    'version' : '1.0',
    'summary': 'Customize user model',
    'sequence': 10,
    'description': """Adding new fields to user model(employee id and user login count)""",
    'category': 'Accounting/Accounting',
    'website': 'https://www.odoo.com/',
    'depends' : ["base"],
    'data': ['views/user.xml'],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}